#!/run/current-system/sw/bin/python3

"""A simple task manager using stack semantics."""

from __future__ import annotations

import sys

if not sys.platform.startswith('darwin'):
    _err = 'This application is only supported on macOS.'
    raise RuntimeError(_err)


if __name__ == '__main__':
    if 'view' in sys.argv:
        from lib.viewer_app import ViewerApp

        app = ViewerApp()
    else:
        from lib.stack_app import StackApp

        app = StackApp()

    app.run()
